### ISSUE TITLE
Blue note: Styles

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#60]
I thought I had done this one but it looks like I didn't!

Let's make sure that theme.json defines the global styles for the theme correctly using this as a guide. If the templates suggest that these numbers are wrong, let's follow the templates over this. 

![Styles](https://github.com/WordPress/community-themes/assets/3593343/fbd7268b-dc19-41de-8369-d25e56f7e955)

**Comment by carolinan** [comment]
I tried adding the secondary color to the links active and focused state but in my opinion the color contrast between the background and link color is too low: Contrast Ratio: 2.01:1.

To my knowledge, this does not pass WCAG 2 AA because there is no change in the text decoration. If for example the underline was also changed, then if I remember correctly, it would technically pass.
Edit: For focus, the focus outline might be enough.

**Comment by carolinan** [comment]
For the buttons, I tried styling the variations so that button one would be the "outline" style variation and button two would be the default.
But styles > blocks > block name > variations > variation name  does not support:
- elements
- hover /active/ focus
- custom css.
